# -*- coding: utf-8 -*-
"""latihan 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Slh82XS5xKHUcwgL2aMnuEKzyfIob264
"""

print ("ini adalah tugas latihan 1")

print ("belajar memahami python")